name: 🛠️ Admin Panel Bug
description: Report an issue related to the Admin Panel like tournament creation, ID sharing, or dashboard bugs.
title: '[Admin Bug] '
labels: ["bug", "admin-panel"]
body:
  - type: textarea
    attributes:
      label: Description of the Bug
      id: description
      description: Please describe what’s going wrong with the admin panel. Be specific about which feature is not working (e.g., add tournament, update prize, etc.).
      placeholder: "For example: When I try to add a new tournament, the form doesn't submit and shows a blank screen."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      id: steps
      description: Please provide a step-by-step guide to reproduce the issue.
      placeholder: |
        1. Login to Admin Panel
        2. Click on 'Add Tournament'
        3. Fill all fields and click Submit
        4. Observe the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots or Screen Recording (if applicable)
      id: screenshots
      description: Upload screenshots or a screen recording showing the issue.
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Not browser-related (for backend or API)
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Information
      id: extra
      description: Any other context or error logs you want to share.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked for existing issues related to this
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/mdazfar2/DBGMI-Playzone/blob/main/CONTRIBUTING.md)
          required: true
        - label: I am willing to work on this issue
          required: false
